### ISSUE TITLE
Unable to sign up an user

### ISSUE THREAD

**Issue by kamesh231** [strongloop/loopback-example-user-management#10]
I tried using ur example to check how the code works but unfortunately after user sign up , I find a page not found error. Wondering what could be the reason. Could you please help.

P.S. I'm new to node js and finding it tough to understand. :(

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
