### ISSUE TITLE
How to add user details using relations ?

### ISSUE THREAD

**Issue by maisnamraju** [strongloop/loopback-example-user-management#11]
I have looked at the loopback angular admin project and I have not been able to find a way to add user details for the user. How can I do this ?
I want to store the users details like first name, last name and mobile number in a seperate model and and upon registration store them in their respective models. Hope it makes sense.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
