### ISSUE TITLE
User management using Angular SDK

### ISSUE THREAD

**Issue by ghost** [strongloop/loopback-example-user-management#12]
Please have a version with angular SDK. I've tried creating an application using the same but got stuck with logout and password reset. Can you help?

**Comment by marcoserafini2** [comment]
I sketched integration of the project with angular
https://github.com/marcoserafini2/loopback-example-user-management

**Comment by superkhau** [comment]
@marcoserafini2 Nice, do you want to rename it `loopback-example-user-management-angular` or something to make it obvious? Can we add it to our list of community projects at http://loopback.io/community?

@crandmck ^

**Comment by marcoserafini2** [comment]
Ok, I renamed the repository :smile:

**Comment by crandmck** [comment]
@marcoserafini2 If you want to add your project to the "Community projects" section of the LoopBack docs, follow the instructions in http://loopback.io/doc/en/community/How-to-add-a-project.html.  Let me know if you have questions or need any help.  Thanks!
