### ISSUE TITLE
Bug in the example code?

### ISSUE THREAD

**Issue by shairez** [strongloop/loopback-example-user-management#13]
in  -

https://github.com/strongloop/loopback-faq-user-management/blob/master/common/models/user.js#L21

There is no `next()` function declared

Is it suppose to be the 3rd param of the `afterRemote` function ?

**Comment by superkhau** [comment]
Closing as your PR has been merged. Thanks again for the contribution.

**Comment by kgoedecke** [comment]
Issue still not resolved see my pull request https://github.com/strongloop/loopback-example-user-management/pull/27
