### ISSUE TITLE
Use of deprecated afterCreate model hook

### ISSUE THREAD

**Issue by andressrg** [strongloop/loopback-example-user-management#21]
The deprecated `afterCreate` model hook is being used [here](https://github.com/strongloop/loopback-example-user-management/blob/3a8a26642cc74ac0b5f98434828b84e44b6af847/common/models/user.js#L6)

The [docs](https://docs.strongloop.com/display/public/LB/Model+hooks) indicate Operation hooks should be used instead.

**Comment by andressrg** [comment]
I tried to fix it myself by using `user.observe('after save' ...` and checking `context.isNewInstance` before calling `validate`, but couldn't find a way to access `context.res` from inside the Operation hook to render the final response.

Is there a way to get the `res` from inside the `after save` Operation hook?

**Comment by richardpringle** [comment]
Hey @andressrg, do you ever manage to get this fixed? If you're still interested in working on it, maybe you can put it in a public repo and I can take a look and try to help you. If I am not mistaken, I think you're looking for `context.instance` property?

**Comment by talpasco** [comment]
Any update about that?

**Comment by richardpringle** [comment]
The `afterCreate` model hook is no longer being used, it has been replaced with the `afterRemote('create', ...)` remote hook. [See here for details.](https://github.com/strongloop/loopback-example-user-management/blob/master/common/models/user.js#L6)

**Comment by talpasco** [comment]
I am using "afterRemote('create', ...)". Just downloaded the example as-is.
After signing up, I'm being redirected to: "/api/users" and "user.afterRemote('confirm', function(context, user, next)" isn't firing at any-time (So I can't verify the user, and no mail is being sent).
Any chance you're able to replicate the problem or is it just me?
Thanks,
Tal

**Comment by richardpringle** [comment]
you mean `user.afterRemote('create`, ...)`?

**Comment by talpasco** [comment]
Yes. Sorry about that.
I meant "user.afterRemote('create', function(context, user, next)", 
that never gets triggered...

**Comment by richardpringle** [comment]
@talpasco, do you think you could open a new issue for this please?

**Comment by talpasco** [comment]
I have... #34 
I rolled back to an older version and it worked.
This is probably also relevant for: https://github.com/strongloop/loopback-example-passport/issues/42#issuecomment-202402133
