### ISSUE TITLE
Some Doubts

### ISSUE THREAD

**Issue by masalinas** [strongloop/loopback-example-user-management#22]
I was reading your example and using in angular. I'm going to resume the process and make the question:

  1) You fill a form sending your email and requesting a reset password.
  2) The server side get this request, create a temporal token against this user email, and send a reset confirmation email to this user email attaching the token id.
  3) The user link this email and the server again take this token id and oipen a new form when the user set the new password. Accept the form.
 4) The server take this form click and the token id. The questions are: 
 ¿How you can recover the user Id if this data is not send by the form?, because in your code you write this:

   User.findById(req.accessToken.userId, function(err, user) { ... }

   Which is the origin of this data req.accessToken.userId?, because we only have the accessToken, that is, the access token id only.

  So if I must recover the user id before reseting the password, How can i recover this data from the standard api, or I must to create a custom api for this query?.

Other question is, the temporal access token created before, I must to remove it??

Regards.

**Comment by richardpringle** [comment]
Hey @masalinas, we're actually reserving the "issues" section of GitHub for bugs and feature requests. Please post any questions here: https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

Hopefully someone can help you there!
If you get an answer and find that there really is an issue, you can open up a new ticket.
