### ISSUE TITLE
Sample not running

### ISSUE THREAD

**Issue by PhilippeCorreges** [strongloop/loopback-example-user-management#23]
Hello,
I cloned the source code form github.
I ran a nom install and run the server.
When clicking on the register button, I am getting this error:
> user.afterRemote triggered
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: next is not a function
    at /WebstormProjects/user-management/loopback-example-user-management/common/models/user.js:20:23
    at/WebstormProjects/user-management/loopback-example-user-management/node_modules/loopback/common/models/user.js:421:11

**Comment by richardpringle** [comment]
Hey @PhilippeCorreges, thanks for pointing out the issue! We'll get it fixed as soon as we can.

**Comment by PhilippeCorreges** [comment]
Your are welcome

**Comment by richardpringle** [comment]
Fix was applied here #27. Closing.

**Comment by git2g** [comment]
The error is still happening  @richardpringle and @bajtos : 

>  throw er; // Unhandled 'error' event
      ^

TypeError: next is not a function
> 

I have:
`Model.beforeRemote('*.__get__hasManyModel', function doSomething(ctx, next){ next(); })`
