### ISSUE TITLE
Merge passport example into this repo

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-example-user-management#25]
Per https://github.com/strongloop/loopback/issues/1758 in order to reduce the total number of example repos, we would like to add the passport functionality from [loopback-example-passport](https://github.com/strongloop/loopback-example-passport) into this example repo.  Presumably, this would just involve adding the option to add passport-based 3d party login to this app.  If you have questions, please ping me or @superkhau.

**Comment by richardpringle** [comment]
Just to confirm, @crandmck and @superkhau, I'm not doing this? Can one of you close then please?

**Comment by superkhau** [comment]
@richardpringle You should create another issue to make sure this app is updated instead though. ;)
