### ISSUE TITLE
How can I detect login and logout events?

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback-example-user-management#30]
Is there a way to subscribe to the user login and logout events? Like a login hook? It would be quite useful, since a lot of logic can be tied to such stuff.

**Comment by richardpringle** [comment]
@barocsi, sorry about the delayed response. Extend the built-in user model and use a remote hook:
```node
user.afterRemote('login', (ctx, user, next) => {
  // do something...
  next();
})
```

For future reference, please post any questions to one (or more) of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

You will probably get a more timely response!
