### ISSUE TITLE
`req.accessToken` === `null`

### ISSUE THREAD

**Issue by smirnovshina** [strongloop/loopback-example-user-management#31]
There is a note in README.md:
> We use the LoopBack token middleware to process access tokens. As long as you provide access_token in the query string of URL, the access token object will be provided in req.accessToken property in your route handler

I provide an `access_token` in url and try to get it with `req.accessToken` in the route handler and there is no access token, `null` instead. How to get access token?

**Comment by smirnovshina** [comment]
I think I figure it out.

**Comment by totymedli** [comment]
If your access token is stored in the cookies you can get it from `req.headers.cookie`. Example cookie retrieval in a route:

```js
module.exports = function (server) {
  let router = server.loopback.Router()
  router.get('/', (req, res) => {
    res.send(req.headers.cookie)
  })
  server.use(router)
}
```
