### ISSUE TITLE
From equals to To when resetting password

### ISSUE THREAD

**Issue by PhilippeCorreges** [strongloop/loopback-example-user-management#33]
Workflow to reproduce :

- Clone this repository and set a mail datasource.
- Register a user
- On the home page click on the reset password link and enter the user email entered above.
- The user is receiving the message with a From equals to its email address.

I tested it with gmail

**Comment by richardpringle** [comment]
Sorry @PhilippeCorreges, your wording is a little confusing.
Say the user's email is `user@loopback.com`, what you're saying is the `FROM` field and the `TO` field have the same values?

**Comment by richardpringle** [comment]
@PhilippeCorreges, ignore the above comment. I see what you're talking about. It was actually done on purpose in this example assuming that you want to send the first email to yourself as a test. I updated [the README](https://github.com/strongloop/loopback-example-user-management/blob/master/README.md#how-do-you-perform-a-password-reset-for-a-registered-user) to justify this. 

I will close the issue, but please comment and mention me directly if you wish to carry on a discussion.
