### ISSUE TITLE
User Management & MySQL

### ISSUE THREAD

**Issue by talpasco** [strongloop/loopback-example-user-management#36]
Running this example on memory DB, it runs perfectly.
But, using MySQL as data-source, produce the following error:
> C:\loopback-example-access-control\node_modules\mysql\lib\protocol\Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^
 ValidationError: The `user` instance is not valid. Details: `email` is invalid (value: "john@doe.com"); `username` is invalid (value: "John").,ValidationError: The `user` instance is not valid. Details: `email` is invalid (value: "jane@doe.com"); `username` is invalid (value: "Jane").,ValidationError: The `user` instance is not valid. Details: `email` is invalid (value: "bob@projects.com"); `username` is invalid (value: "Bob").

Thanks,
Tal

**Comment by richardpringle** [comment]
Hey @talpasco, can you do me two huge favors? Can you fork this repo and write the steps to reproduce? I want to make sure you have set up your datasource properly. Also might be a good idea to test other models and see if anything works.

I can't think of any reason why the example wouldn't work on one datasource over the other.

**Comment by talpasco** [comment]
I'm really (really) sorry... This project runs flawlessly with MySQL.
The project that doesn't is: https://github.com/strongloop/loopback-example-access-control
So I'll ask the question over there.
Again, sorry.

**Comment by richardpringle** [comment]
Haha no worries, it's probably going to be me responding over there too!
