### ISSUE TITLE
email example dead link

### ISSUE THREAD

**Issue by xgdgsc** [strongloop/loopback-example-user-management#37]
https://github.com/strongloop/loopback-example-email in README is deadlink

**Comment by superkhau** [comment]
Which link are you refering to specifically?

**Comment by xgdgsc** [comment]
[configure LoopBack to send email]

**Comment by pbrain19** [comment]
same here :+1:

**Comment by pbrain19** [comment]
like how can I see the variables that I am allowed to use for the email verification?

**Comment by richardpringle** [comment]
@xgdgsc @pbrain19, I fixed the dead link for you guys. I will close this issue but please feel free to carry on the conversation in here. Make sure to mention me or @superkhau if you have any further questions.
