### ISSUE TITLE
How do I modify template?

### ISSUE THREAD

**Issue by pbrain19** [strongloop/loopback-example-user-management#39]
Is there documentation on what variables I get back to use in my ejs templates? I want to be able to use a template that contains the ejs variables such as auth link or what not.

**Comment by richardpringle** [comment]
@pbrain19 

Check out this file, [routes.js](https://github.com/strongloop/loopback-example-user-management/blob/master/server/boot/routes.js).

That's where all the routes get set. 

Closing the issue, but please feel free to ask any other questions in here and mention me in the comment.
