### ISSUE TITLE
How to customize the verify email link?

### ISSUE THREAD

**Issue by grimpa** [strongloop/loopback-example-user-management#56]
Hi everyone, Hi @superkhau,

I need to change the pattern of the email verify url. How to customize the verify url in this case when I using the user model extended.

The verifyHref is concatenated in verify method. But I would to define my full link.

For example: The actual link is generated like this:
```
http://domain:3000/?uid=XXX&redirect=YYY&verificationToken=ZZZ
```
I would like my link to look like this:
```
http://domain:3000/YYY/ZZZ
```
Being the YYY the user id and ZZZ the verificationToken

Someone can help?
Thanks.

**Comment by grimpa** [comment]
Solved!

I created a private/custom method in the extended model to customize it my way.
Basically I duplicated the verify method and made my necessary changes.

I hope this helps somebody.

**Comment by anurento** [comment]
@grimpa Hey I need help to do this. Can you please provide the sample code.

Thanks
