### ISSUE TITLE
Is creating a your own model user that extends the base model User best practice? 

### ISSUE THREAD

**Issue by vespertilian** [strongloop/loopback-example-user-management#7]
In your example you have User "public: false" and a lower case user model. Is this best practice? If it is, I feel it would be worthwhile to explicitly state that in this example documentation.  

  "User": {
    "dataSource": "db",
    "public": false
  },

 "user": {
    "dataSource": "db",
    "public": true,
    "options": {
      "emailVerificationRequired": true
    }
  }

**Comment by kpullen** [comment]
There seems to have been a lot of discussion about this in strongloop/loopback#397. @pulkitsinghal created a [gist](https://gist.github.com/pulkitsinghal/43d4bae2467c686ec55b) that shows some ways you can upgrade an existing model. I've got a solution on my [fork](https://github.com/kpullen/loopback-faq-user-management). The relevant file is `server/boot/01-upgrade-user-model.js`.

**Comment by superkhau** [comment]
Yes, see https://docs.strongloop.com/display/public/LB/Managing+users#Managingusers-Overview.

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
