### ISSUE TITLE
Openshift verification link

### ISSUE THREAD

**Issue by PeterClough** [strongloop/loopback-example-user-management#8]
Hi just got all this working with a few changes because I use the Angular SDK so I don't want all the server redirects. It all works fine at home but when I click the verification link which is of the form host:port/api.... the webpage hangs if I change host:port to be my website name it fires through.

Any chance somewhere in the config there could be an option to override the host port with the website name if its defined in options please? or can you suggest another change? I can't even hack the server code because Openshift builds it

**Comment by saubhagyab** [comment]
I am understanding it correctly you want to override the href link which is sent on your email. So for doing so you can go into the default users.js under loopback/models and change it.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
